# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oppo/neo5/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/oppo/neo5/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/oppo/neo5/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/oppo/neo5/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/oppo/neo5/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/oppo/neo5/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/oppo/neo5/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/oppo/neo5/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/oppo/neo5/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/oppo/neo5/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/oppo/neo5/proprietary/lib/hw/camera.msm8226.so:system/lib/hw/camera.msm8226.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libmmcamera_hi258.so:system/vendor/lib/libmmcamera_hi258.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libmmcamera_hi256.so:system/vendor/lib/libmmcamera_hi256.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libmmcamera_hi258_14013.so:system/vendor/lib/libmmcamera_hi258_14013.so \
    vendor/oppo/neo5/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libchromatix_ov5648_back_common.so:system/vendor/lib/libchromatix_ov5648_back_common.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libchromatix_ov5648_liveshot.so:system/vendor/lib/libchromatix_ov5648_liveshot.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libchromatix_ov5648_back_default_video.so:system/vendor/lib/libchromatix_ov5648_back_default_video.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libchromatix_ov5648_liveshot_truly.so:system/vendor/lib/libchromatix_ov5648_liveshot_truly.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libchromatix_ov5648_back_hdr_shot.so:system/vendor/lib/libchromatix_ov5648_back_hdr_shot.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libchromatix_ov5648_preview.so:system/vendor/lib/libchromatix_ov5648_preview.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libchromatix_ov5648_back_liveshot.so:system/vendor/lib/libchromatix_ov5648_back_liveshot.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libchromatix_ov5648_preview_truly.so:system/vendor/lib/libchromatix_ov5648_preview_truly.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libchromatix_ov5648_back_preview.so:system/vendor/lib/libchromatix_ov5648_back_preview.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libchromatix_ov5648_vga.so:system/vendor/lib/libchromatix_ov5648_vga.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libchromatix_ov5648_back_zsl.so:system/vendor/lib/libchromatix_ov5648_back_zsl.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libchromatix_ov5648_vga_truly.so:system/vendor/lib/libchromatix_ov5648_vga_truly.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libchromatix_ov5648_common.so:system/vendor/lib/libchromatix_ov5648_common.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libchromatix_ov5648_default_video.so:system/vendor/lib/libchromatix_ov5648_default_video.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libchromatix_ov5648_zsl.so:system/vendor/lib/libchromatix_ov5648_zsl.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libchromatix_ov5648_zsl_truly.so:system/vendor/lib/libchromatix_ov5648_zsl_truly.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libchromatix_ov5648_default_video_truly.so:system/vendor/lib/libchromatix_ov5648_default_video_truly.so \
    vendor/oppo/neo5/proprietary/app/TimeService.apk:system/app/TimeService.apk \
    vendor/oppo/neo5/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/oppo/neo5/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/oppo/neo5/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/oppo/neo5/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/oppo/neo5/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/oppo/neo5/proprietary/bin/rild:system/bin/rild \
    vendor/oppo/neo5/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libdsnetutils.so:system/vendor/lib/libdsnetutils.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so \
    vendor/oppo/neo5/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/oppo/neo5/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/oppo/neo5/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/oppo/neo5/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/oppo/neo5/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/oppo/neo5/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/oppo/neo5/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/oppo/neo5/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    vendor/oppo/neo5/proprietary/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
    vendor/oppo/neo5/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so
